name: CI

'on':
    pull_request:
    push:
        branches:
          - second_edition

env:
    UBSAN_OPTIONS: print_stacktrace=1
    ASAN_OPTIONS: detect_odr_violation=2

jobs:
    posix:
        strategy:
            fail-fast: false
            matrix:
                include:
                  - CXX_FLAGS: --coverage -fsanitize=address,leak,undefined
                    LINK_FLAGS: --coverage
                    QLIBS: -lasan -lubsan
                    TOOLSET: gcc-12
                    CXXTOOLSET: g++-12
                    GCOV: --gcov-tool gcov-6
                    os: ubuntu-24.04
                    info: gcc-12


        name: '${{matrix.os}}: ${{matrix.info}}'
        runs-on: ${{matrix.os}}

        steps:
          - uses: actions/checkout@v4

          - name: Install deps
            run: |
                sudo apt update
                sudo apt install --allow-downgrades -y git python3-yaml gcc-12 g++-12 qt4-qmake language-pack-ru gdb libc++-dev

          - name: Install Boost
            run: |
                PROJECT_DIR=`pwd`
                BOOST=$HOME/boost-local
                git init $BOOST
                cd $BOOST
                git remote add --no-tags -t $BRANCH_TO_TEST origin https://github.com/boostorg/boost.git
                git fetch --depth=10
                git checkout $BRANCH_TO_TEST
                git submodule update --init --merge >/dev/null
                git status
                ./bootstrap.sh
                ./b2 headers
                ./b2 -j4 toolset=$TOOLSET address-model=64 architecture=x86 link=shared --with-program_options --with-filesystem --with-system --with-test --with-atomic --with-thread --with-timer --with-chrono --with-regex --with-random --with-context stage
                cd $PROJECT_DIR

          - name: Run qmake
            run: |
                qmake "QMAKE_CXX=${{ matrix.CXXTOOLSET }}" "QMAKE_LINK=${{ matrix.CXXTOOLSET }}" "QMAKE_CXXFLAGS+=${{ matrix.CXX_FLAGS }}" "QMAKE_LFLAGS+=${{ matrix.LINK_FLAGS }}" "LIBS+=${{ matrix.QLIBS }}" "BOOST_PATH=$HOME/boost-local" "CONFIG+=debug" BoostBook.pro

          - name: Build
            run: |
                make -j4

          - name: Test
            run: |
                python ./test.py -v

